export const changelog = [
  [
    'Number keys updated to select that specific enabled edit mode',
    'Adding direct face color edit modes for outside/inside',
  ],
  [
    '2024-06-10',
    'Removing edge controls on pure coloring view mode',
    'Removing face color controls on basic edge/sector view modes',
    'Added tooltips',
    'Layer hint annotations in front of selected face color',
    'Only show custom options when custom AND advanced options are selected',
    'Added ctrl-y redo shortcut',
    'Added option for showing elapsed time (timer)',
    'Clear pending actions when requesting a hint',
    'Moved hint CPU processing to a web worker',
    'Rearranged classic view mode to first',
    'Clear hints on escape key',
    'Separate hint information section',
    'Working around weird aliasing on Chrome',
    'Improve edit mode switches on view style switches',
    'Auto-pan to hint',
    'Add shift + scroll for horizontal scrolling',
    'Slightly increased size/spacing of edit mode buttons',
    'Added options to control error highlighting / number dimming',
    'Added slight delay lockout on autosolved edges (for usability)',
    'Miscellaneous fixes!',
  ],
];
